name: CI Build
on:
  push:
    branches:
      - docker
  pull_request:
    branches:
      - docker
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies #first install all the things you will need
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Lint with flake8 #lint the code to check for PEP 8 compliance
        run: |
          flake8 